"use server";

import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

const FREE_SHIP = 15000;
const SHIP_FEE = 250;

const itemSchema = z.object({
  productId: z.string().min(1),
  size: z.string().default("Unstitched"),
  color: z.string().default("Default"),
  quantity: z.coerce.number().int().min(1).max(20),
});

const orderSchema = z.object({
  name: z.string().trim().min(2, "Please enter your name"),
  email: z.email("Enter a valid email"),
  phone: z.string().trim().min(7, "Enter a valid phone number"),
  address: z.string().trim().min(5, "Enter your address"),
  city: z.string().trim().min(2, "Enter your city"),
  postal: z.string().trim().optional(),
  notes: z.string().trim().max(500).optional(),
  payment: z.enum(["cod", "advance"]).default("cod"),
  items: z.array(itemSchema).min(1, "Your bag is empty"),
});

export type PlaceOrderInput = z.input<typeof orderSchema>;

export interface PlaceOrderResult {
  orderNumber?: string;
  total?: number;
  error?: string;
  fieldErrors?: Record<string, string>;
}

export async function placeOrderAction(
  input: PlaceOrderInput,
): Promise<PlaceOrderResult> {
  const parsed = orderSchema.safeParse(input);
  if (!parsed.success) {
    const fieldErrors: Record<string, string> = {};
    for (const issue of parsed.error.issues) {
      const k = String(issue.path[0] ?? "form");
      if (!fieldErrors[k]) fieldErrors[k] = issue.message;
    }
    return { fieldErrors, error: "Please check the highlighted fields." };
  }
  const data = parsed.data;

  const admin = createAdminClient();

  // Fetch authoritative product data (never trust client prices).
  const ids = [...new Set(data.items.map((i) => i.productId))];
  const { data: products, error: pErr } = await admin
    .from("products")
    .select("id, slug, sku, title, price, sale_price, stock")
    .in("id", ids);
  if (pErr || !products?.length) {
    return { error: "We couldn't verify these items. Please try again." };
  }
  const byId = new Map(products.map((p) => [p.id, p]));

  // Build order items + subtotal from server-side prices.
  const orderItems = [];
  let subtotal = 0;
  for (const item of data.items) {
    const p = byId.get(item.productId);
    if (!p) return { error: "One of the items is no longer available." };
    const price = Number(p.sale_price ?? p.price);
    const lineTotal = price * item.quantity;
    subtotal += lineTotal;
    orderItems.push({
      product: p,
      title: p.title,
      slug: p.slug,
      sku: p.sku,
      price,
      size: item.size,
      color: item.color,
      quantity: item.quantity,
      line_total: lineTotal,
    });
  }

  const shippingFee = subtotal >= FREE_SHIP ? 0 : SHIP_FEE;
  const total = subtotal + shippingFee;

  // Link the order to a signed-in customer if there is one.
  let userId: string | null = null;
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    userId = user?.id ?? null;
  } catch {
    userId = null;
  }

  // Create the order (order_number auto-generated by trigger).
  const { data: order, error: oErr } = await admin
    .from("orders")
    .insert({
      user_id: userId,
      status: "pending",
      email: data.email,
      phone: data.phone,
      customer_name: data.name,
      shipping: {
        line1: data.address,
        city: data.city,
        postal_code: data.postal ?? null,
        country: "Pakistan",
      },
      subtotal,
      discount: 0,
      shipping_fee: shippingFee,
      total,
      payment_method: data.payment,
      payment_status: "unpaid",
      advance_amount: 0,
      notes: data.notes ?? null,
    })
    .select("id, order_number")
    .single();

  if (oErr || !order) {
    return { error: "Something went wrong placing your order. Please try again." };
  }

  // Insert order items.
  const { error: iErr } = await admin.from("order_items").insert(
    orderItems.map((it) => ({
      order_id: order.id,
      product_id: it.product.id,
      title: it.title,
      slug: it.slug,
      sku: it.sku,
      price: it.price,
      size: it.size,
      color: it.color,
      quantity: it.quantity,
      line_total: it.line_total,
    })),
  );
  if (iErr) {
    // Roll back the order so we don't leave an empty one behind.
    await admin.from("orders").delete().eq("id", order.id);
    return { error: "Something went wrong placing your order. Please try again." };
  }

  // Decrement stock (clamped at 0).
  await Promise.all(
    orderItems.map((it) =>
      admin
        .from("products")
        .update({ stock: Math.max(0, (it.product.stock ?? 0) - it.quantity) })
        .eq("id", it.product.id),
    ),
  );

  return { orderNumber: order.order_number, total };
}

// ---------- Track order ----------------------------------------------------
const trackSchema = z.object({
  orderNumber: z.string().trim().min(4),
  email: z.email("Enter the email used on the order"),
});

export interface TrackedOrder {
  orderNumber: string;
  status: string;
  total: number;
  paymentMethod: string;
  createdAt: string;
  items: { title: string; quantity: number }[];
}

export async function trackOrderAction(
  _prev: { order?: TrackedOrder; error?: string },
  formData: FormData,
): Promise<{ order?: TrackedOrder; error?: string }> {
  const parsed = trackSchema.safeParse({
    orderNumber: formData.get("orderNumber"),
    email: formData.get("email"),
  });
  if (!parsed.success) {
    return { error: "Enter your order number and the email used on the order." };
  }

  const admin = createAdminClient();
  const { data: order } = await admin
    .from("orders")
    .select("id, order_number, status, total, payment_method, created_at, email")
    .ilike("order_number", parsed.data.orderNumber.trim())
    .ilike("email", parsed.data.email.trim())
    .maybeSingle();

  if (!order) {
    return { error: "No order found with that number and email. Please check and try again." };
  }

  const { data: items } = await admin
    .from("order_items")
    .select("title, quantity")
    .eq("order_id", order.id)
    .limit(50);

  return {
    order: {
      orderNumber: order.order_number,
      status: order.status,
      total: Number(order.total),
      paymentMethod: order.payment_method,
      createdAt: order.created_at,
      items: items ?? [],
    },
  };
}
